//#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorNone)
#pragma config(Sensor, port5,  touchLED,       sensorNone)
#pragma config(Motor,  motor1, leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6, rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BASE_MOVEMENT_SPEED 43
#define STATE_OUT_OF_TRACK 1
#define STATE_ON_TAPE 2
#define STATE_ON_BASE 3
#define STATE_RUN_ENDED 4

task main()
{
	setColorMode(port3, colorTypeRGB_Hue_Reflected);
	int notSeenTapeCount = 0;
	int unsigned long runStartTime = 0;
	int unsigned long runEndTime = 0;
	int movementSpeed = 0;
	int currentState;
	string currentStateString;
	while (1) {
		int redValue = getColorRedChannel(port3);
		int blueValue = getColorBlueChannel(port3);
		int greenValue = getColorGreenChannel(port3);
		int combinedColorValue = redValue + blueValue + greenValue;
		int runTime = nPgmTime;
		if (currentState == STATE_RUN_ENDED) {
			runTime = runEndTime;

			setMotorSpeed(motor1, 0);
			setMotorSpeed(motor6, 0);
			displayTextLine(0, "Run endeded");
			displayTextLine(1, "Runtime: %d", runTime / 1000);
			continue;
		}
		if (35 < redValue && redValue < 45 && 35 < blueValue && blueValue < 45) {
			currentState = STATE_ON_BASE;
			currentStateString = "On base";
		}
		else if (combinedColorValue < 300) {
			currentState = STATE_ON_TAPE;
			currentStateString = "On tape";
		}
		else if (combinedColorValue > 300) {
			currentState = STATE_OUT_OF_TRACK;
			currentStateString = "Out of track";
		}

		displayTextLine(0, "Runstate: %s", currentStateString);
		displayTextLine(1, "Red value: %d", redValue);
		displayTextLine(2, "Blue value: %d", blueValue);
		displayTextLine(3, "Green value: %d", greenValue);
		displayTextLine(4, "Running time: %d", (runTime - runStartTime) / 1000);

		if (currentState == STATE_ON_BASE) {
			// Alustetaan aloitusaika
			if (runStartTime == 0) {
				runStartTime = nPgmTime;
			}
			// Ollaan alussa, menn‰‰n pois l‰htˆpisteelt‰
			// AIKAA KAKSI SEKUNTIAA!!!
			if (nPgmTime - runStartTime < 2000) {
				movementSpeed = BASE_MOVEMENT_SPEED;
				setMotorSpeed(motor1, movementSpeed / 2);
				setMotorSpeed(motor6, movementSpeed / 2);
			}
			else {
				if (runEndTime == 0) {
					runEndTime = nPgmTime;
				}
				currentState = STATE_RUN_ENDED;
				continue;
			}
		}
		else if (currentState == STATE_ON_TAPE) {
			// Teipill‰, tiukka k‰‰ntˆ oikealle
			setMotorSpeed(motor1, movementSpeed * 0.5);
			setMotorSpeed(motor6, movementSpeed * -1);
			notSeenTapeCount = 0;
		}
		else {
			// Ei n‰hd‰ teippi‰, eteenp‰in loivasti vasemmalle
			int leftMotorSpeed = 0;
			if (notSeenTapeCount > 100) {
				// Jyrkent‰‰ k‰‰ntymist‰ jos teippi‰ ei n‰hty pitk‰‰n aikaan
				leftMotorSpeed = movementSpeed / 4 - movementSpeed * notSeenTapeCount / 150;
				if (leftMotorSpeed < -100) {
					leftMotorSpeed = -100;
				}
			}
			else {
				leftMotorSpeed = movementSpeed / 4;
			}
			setMotorSpeed(motor1, leftMotorSpeed);
			setMotorSpeed(motor6, movementSpeed);
			notSeenTapeCount++;
		}
	}
}
