//#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorNone)
#pragma config(Sensor, port5,  touchLedMovementSpeed,       sensorVexIQ_LED)
#pragma config(Sensor, port2,  touchLedTurningSpeed,       sensorVexIQ_LED)
#pragma config(Motor,  motor1, leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6, rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BASE_MOVEMENT_SPEED 40
#define MAX_MOVEMENT_SPEED 55
#define MIN_MOVEMENT_SPEED 30
#define STATE_OUT_OF_TRACK 1
#define STATE_ON_TAPE 2
#define STATE_ON_BASE 3
#define STATE_RUN_ENDED 4
#define STATE_RUN_NOT_STARTED 5

task main()
{
	setColorMode(port3, colorTypeRGB_Hue_Reflected);
	int notSeenTapeCount = 0;
	int unsigned long runStartTime = 0;
	int unsigned long runEndTime = 0;
	int movementSpeed = 0;
	int currentState = STATE_RUN_NOT_STARTED;
	string currentStateString = "Not started";
	while (1) {
		int redValue = getColorRedChannel(port3);
		int blueValue = getColorBlueChannel(port3);
		int greenValue = getColorGreenChannel(port3);
		int combinedColorValue = redValue + blueValue + greenValue;
		int runTime = nPgmTime;
		if (currentState == STATE_RUN_ENDED) {
			runTime = runEndTime;

			setMotorSpeed(motor1, 0);
			setMotorSpeed(motor6, 0);
			displayTextLine(0, "Run endeded");
			displayTextLine(1, "Runtime: %d", (runTime - runStartTime) / 1000);
			displayTextLine(2, "\o/ \O/");
			displayTextLine(3, "woo WOO woo!!1");
			displayTextLine(4, "mage on ylbee xD");
			continue;
		}
		if (35 < redValue && redValue < 45 && 35 < blueValue && blueValue < 45) {
			currentState = STATE_ON_BASE;
			currentStateString = "On base";
		}
		else if (currentState == STATE_RUN_NOT_STARTED) {
			//woot
		}
		else if (combinedColorValue < 300) {
			currentState = STATE_ON_TAPE;
			currentStateString = "On tape";
		}
		else if (combinedColorValue > 300) {
			currentState = STATE_OUT_OF_TRACK;
			currentStateString = "Out of track";
		}

		displayTextLine(0, "Runstate: %s", currentStateString);
		displayTextLine(1, "Current speed: %d", movementSpeed);
		displayTextLine(2, "Running time: %d", (runTime - runStartTime) / 1000);

		if (currentState == STATE_ON_BASE) {
			// Alustetaan aloitusaika
			if (runStartTime == 0) {
				runStartTime = nPgmTime;
			}
			// Ollaan alussa, menn‰‰n pois l‰htˆpisteelt‰
			// AIKAA KAKSI SEKUNTIAA!!!
			if (nPgmTime - runStartTime < 2000) {
				movementSpeed = BASE_MOVEMENT_SPEED;
				setMotorSpeed(motor1, movementSpeed / 2);
				setMotorSpeed(motor6, movementSpeed / 2);
			}
			else {
				if (runEndTime == 0) {
					runEndTime = nPgmTime;
				}
				currentState = STATE_RUN_ENDED;
				continue;
			}
		}
		else if (currentState == STATE_ON_TAPE) {
			// Teipill‰, tiukka k‰‰ntˆ oikealle
			setMotorSpeed(motor1, movementSpeed * 0.5);
			setMotorSpeed(motor6, movementSpeed * -1);
			if (notSeenTapeCount <= 60 && notSeenTapeCount > 0) {
				setTouchLEDColor(port5, colorBlue);
				movementSpeed -= 10;
				if (movementSpeed < MIN_MOVEMENT_SPEED) {
					movementSpeed = MIN_MOVEMENT_SPEED;
				}
			}
			else if (notSeenTapeCount > 60) {
				setTouchLEDColor(port5, colorGreen);
				movementSpeed += 3;
				if (movementSpeed > MAX_MOVEMENT_SPEED) {
					setTouchLEDColor(port5, colorRed);
					movementSpeed = MAX_MOVEMENT_SPEED;
				}
			}
			notSeenTapeCount = 0;
		}
		else {
			// Ei n‰hd‰ teippi‰, eteenp‰in loivasti vasemmalle
			int leftMotorSpeed = 0;
			if (notSeenTapeCount > 25 && notSeenTapeCount < 100) {
				leftMotorSpeed = movementSpeed / 6;
				setTouchLEDColor(port2, colorBlue);
			}
			else if (notSeenTapeCount > 150) { // T‰t‰ arvoa kannattaa pienent‰‰ jos menee suoran j‰lkeen mutkat pitk‰ksi
				setTouchLEDColor(port2, colorRed);
				// Jyrkent‰‰ k‰‰ntymist‰ jos teippi‰ ei n‰hty pitk‰‰n aikaan
				leftMotorSpeed = movementSpeed / 4 - movementSpeed * notSeenTapeCount / 200;
				if (leftMotorSpeed < -2 * BASE_MOVEMENT_SPEED) {
					leftMotorSpeed = -2 * BASE_MOVEMENT_SPEED;
				}
			}
			else {
				setTouchLEDColor(port2, colorGreen);
				leftMotorSpeed = movementSpeed / 4;
			}
			setMotorSpeed(motor1, leftMotorSpeed);
			setMotorSpeed(motor6, movementSpeed);
			notSeenTapeCount++;
		}
	}
}
