//#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorNone)
#pragma config(Sensor, port5,  touchLED,       sensorNone)
#pragma config(Motor,  motor1, leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6, rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MOVEMENT_SPEED 35


task main()
{
	int i = 0;
	setColorMode(port3, colorTypeGrayscale_Reflected);
	bool onTape = false;
	int onTapeGrayThreshold = 255;
	int notSeenTapeCount = 0;
	while (1) {
		if (i > 255) {
			i = 0;
		}
		else {
			i++;
		}

		int grayValue = getColorGrayscale(port3);
		displayTextLine(0, "Grayvalue: %d", grayValue);
		displayTextLine(1, "Threshold: %d", onTapeGrayThreshold);
		//displayTextLine(2, "i: %d", i);
		if (grayValue < onTapeGrayThreshold) {
			onTape = true;
		}
		else {
			onTape = false;
		}
		if (onTape == true) {
			// Teipill‰, tiukka k‰‰ntˆ oikealle
			setMotorSpeed(motor1, MOVEMENT_SPEED);
			setMotorSpeed(motor6, MOVEMENT_SPEED * -1);
			notSeenTapeCount = 0;
		}
		else {
			// Ei n‰hd‰ teippi‰, eteenp‰in loivasti vasemmalle
			int leftMotorSpeed = 0;
			if (notSeenTapeCount > 200) {
				// Jyrkent‰‰ k‰‰ntymist‰ jos teippi‰ ei n‰hty pitk‰‰n aikaan
				leftMotorSpeed = MOVEMENT_SPEED / 4 - MOVEMENT_SPEED * notSeenTapeCount / 400;
				if (leftMotorSpeed < -100) {
					leftMotorSpeed = -100;
				}
			}
			else {
				leftMotorSpeed = MOVEMENT_SPEED / 4;
			}
			setMotorSpeed(motor1, leftMotorSpeed);
			setMotorSpeed(motor6, MOVEMENT_SPEED);
			notSeenTapeCount++;
		}
	}
}
